Bj 1 login,logout,see profile,change details
JuliaSawczenko/BookJourney pull request #2
Opened 2024-01-02 22:49 UTC by JuliaSawczenko

Dodalam endpointy do: **logowania, wylogowania, wyświetlenia profilu, zmiany hasła i nazwiska/imienia**.

Próbowalam użyć interfejsu **UserDetailsManager** (jego metod _change password_, _update user_, etc) ale nie byłam w stanie pokonać blędów (stack overflow).
Utworzyłam endpointy bez tego interfejsu, natomiast jeśli to jest "bad coding",  to daj proszę znać :) 

Plik Procfile jest potrzebny do deploymentu w Heroku.

2024-01-03 15:13 UTC, marzgra commented
następnym razem pamiętaj aby utworzyć nowy branch (po merge możesz go usunąć) lub aby zmienic nazwę.

2024-01-03 15:38 UTC, marzgra requested changes

2024-01-03 15:38 UTC, marzgra commented on src/main/java/com/bookJourney/springboot/controller/UserController.java
> +            Authentication authentication = authenticationManager.authenticate(
controller powinien zawierać minimum logiki biznesowej, może nowe serwis, albo userService mógłby przejąć tę operację?

2024-01-03 15:38 UTC, marzgra commented on src/main/java/com/bookJourney/springboot/controller/UserController.java
> +        boolean isCurrentPasswordCorrect = userService.changePassword(username, passwordChangeDTO);
nazwa flagi nie pokrywa się z działaniem. isCurrentPasswordCorrect sugeruje że sprawdzane jest obecne hasło, a operacja przeprwadza zmianę hasła. proponuję zmianę nazwy flagi na isPasswordSuccessfullyChanged

2024-01-03 15:38 UTC, marzgra commented on src/main/java/com/bookJourney/springboot/controller/UserController.java
> +        boolean isCurrentPasswordCorrect = userService.changePassword(username, passwordChangeDTO);
sugeruję wtedy również odwrócenie warunku w IF, łatwiej się czyta pozytywne warunki ;)

2024-01-03 15:38 UTC, marzgra commented on src/main/java/com/bookJourney/springboot/dto/LoginDTO.java
> +public record LoginDTO(@NotBlank String username,@Size(min = 8) String password) {
pamiętaj o formatowaniu (brak spacji po przecinku).
w przypadku recordów częstą praktyką jest umieszczanie atrybutów od nowej linii czyli:
```
public record LoginDTO(@NotBlank String username,
                       @Size(min = 8) String password) { 
}
```

2024-01-03 15:38 UTC, marzgra commented on src/main/java/com/bookJourney/springboot/dto/LoginDTO.java
> +public record LoginDTO(@NotBlank String username,@Size(min = 8) String password) {
tak samo w innych klasach

2024-01-03 15:38 UTC, marzgra commented on src/main/java/com/bookJourney/springboot/service/UserService.java
> +    private User getUserByUsername(String username) {
są dwa podejścia - albo metoda prywatna zaraz pod metodą publiczną która jej używa, albo najpierw metody publiczne a potem prywatne. zastanów się które podejście bardziej do ciebie przemawia i dostosuj kolejność metod ;)

2024-01-03 15:38 UTC, marzgra commented on src/main/java/com/bookJourney/springboot/service/UserService.java
> +    public void processSuccessfulLogin(String username) {
'process' wskazuje że to tutaj odbywa się cała logika, tak jak wspomniałam w controlerze, możesz przenieść resztę kodu tutaj i zwrócić flagę boolean

2024-01-03 15:38 UTC, marzgra commented on src/test/java/com/bookJourney/springboot/mapper/UserMapperTest.java
> +    public void testUserToProfileDTO() {
jeśli nie używasz opisu w postaci @DisplayName staraj się nazywać testy wg konwencji
should<oczekiwany efekt>When<warunek>
ShouldCorrectlyMapUserToProfileDto (część when nie zawsze musi się pojawic ;) )

2024-01-03 15:38 UTC, marzgra commented on src/test/java/com/bookJourney/springboot/mapper/UserMapperTest.java
> +        assertEquals(user.getFirstName(), dto.firstName());
w assercji warto aby dane usera były brane z mockedValues

2024-01-03 15:38 UTC, marzgra commented on src/test/java/com/bookJourney/springboot/mocks/ProfileDTOMock.java
> +        return new ProfileDTO(USERNAME, FIRST_NAME, LAST_NAME, LocalDate.now());
datę proponuję zastąpić też mockedValue statycznie ustawioną (LocalDate.of(...))

2024-01-04 00:00 UTC, JuliaSawczenko commented
@marzgra zrobiłam poprawki, potwierdz proszę czy mogę mergować :)

2024-01-04 08:54 UTC, marzgra commented on src/main/java/com/bookJourney/springboot/service/AuthenticationService.java
> +    @Autowired
możesz pominąć @Autowired, tymbardziej nie dawaj tej adnotacji na sam konstruktor

2024-01-04 08:55 UTC, marzgra approved these changes

2024-01-04 15:45 UTC, merged